<a href="https://colab.research.google.com/github/jisusP/MachineLearning/blob/main/entornoGrafico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
matriz = []
rows = 5
columns = 5

for i in range(rows):
  fila = []
  for j in range(columns):
    "añadir los números a las filas"
    fila.append(i*columns + j)
  matriz.append(fila)
matriz

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

# ***Matriz centrada***

In [ ]:
import numpy as np

column_mean = np.mean(matriz, axis=0)
X_centre = matriz - column_mean
X_centre

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

# ***Matriz escalada***

In [ ]:
std_columns = np.std(matriz, axis=0)
X_escalada = X_centre/std_columns
X_escalada

[7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]


array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356]])

# ***Matriz SNV***

In [ ]:
row_mean = np.mean(matriz, axis=1).reshape(len(matriz[0]),1)
row_std = np.std(matriz, axis=1).reshape(len(matriz[0]),1)
X_snv = (matriz - row_mean)/row_std
X_snv

array([[-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]])

#***Matriz de derivada***

In [ ]:
dx = []
for i in range(len(matriz)):
  prueba = []
  for j in range(len(matriz[i])-1):
    a = matriz[i][j+1] - matriz[i][j]
    prueba.append(a)
  dx.append(prueba)
dx

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

#***Matriz de normalización***

In [ ]:
import math

columnas_Normalizadas = []
for i in range(len(matriz)):
  colI=[]
  for j in range(len(matriz[i])):
    colI.append(matriz[j][i])
    #print(matriz[i], matriz[j], matriz[j][i], matriz[i][j])
  norma = math.sqrt(sum([x**2 for x in colI]))
  columnas_Normalizadas.append(norma)

X_normalizada = []
print(matriz)
print(columnas_Normalizadas)

for col in matriz:
  conjunto = []
  for id in range(len(col)):
    b = col[id]/columnas_Normalizadas[id]
    conjunto.append(b)
  X_normalizada.append(conjunto)

X_normalizada

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]
[27.386127875258307, 29.24038303442689, 31.144823004794873, 33.090784215548595, 35.07135583350036]


[[0.0,
  0.03419927840283847,
  0.06421612990679355,
  0.09065968278232492,
  0.11405318970244022],
 [0.18257418583505536,
  0.20519567041703082,
  0.22475645467377744,
  0.24175915408619977,
  0.2566196768304905],
 [0.3651483716701107,
  0.37619206243122316,
  0.38529677944076135,
  0.3928586253900746,
  0.39918616395854073],
 [0.5477225575051661,
  0.5471884544454155,
  0.5458371042077452,
  0.5439580966939495,
  0.541752651086591],
 [0.7302967433402214,
  0.7181848464596079,
  0.7063774289747291,
  0.6950575679978244,
  0.6843191382146413]]

#***Matriz de línea base***

In [ ]:
column_min = np.min(matriz, axis=0)
X_Lbase = matriz - column_min
X_Lbase

array([[ 0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15],
       [20, 20, 20, 20, 20]])

#***Funciones***

In [8]:
import numpy as np
import math
def centre(m):
  column_mean = np.mean(m, axis=0)
  X_centre = m - column_mean
  return X_centre

def escalar(m):
  std_columns = np.std(m, axis=0)
  X_escalada = centre(m)/std_columns
  return X_escalada

def SNV(m):
  row_mean = np.mean(m, axis=1).reshape(len(m[0]),1)
  row_std = np.std(m, axis=1).reshape(len(m[0]),1)
  X_snv = (m - row_mean)/row_std
  return X_snv

def derivar(m):
  dx = []
  for i in range(len(m)):
    prueba = []
    for j in range(len(m[i])-1):
      a = m[i][j+1] - m[i][j]
      prueba.append(a)
    dx.append(prueba)
  return dx

def normalizar(m):
  columnas_Normalizadas = []
  for i in range(len(m)):
    colI=[]
    for j in range(len(m[i])):
      colI.append(m[j][i])
      #print(matriz[i], matriz[j], matriz[j][i], matriz[i][j])
    norma = math.sqrt(sum([x**2 for x in colI]))
    columnas_Normalizadas.append(norma)
  X_normalizada = []
  #print(m)
  #print(columnas_Normalizadas)
  for col in m:
    conjunto = []
    for id in range(len(col)):
      b = col[id]/columnas_Normalizadas[id]
      conjunto.append(b)
    X_normalizada.append(conjunto)
  return X_normalizada

def linea_base(m):
  column_min = np.min(m, axis=0)
  X_Lbase = m - column_min
  return X_Lbase


[[0.0,
  0.03419927840283847,
  0.06421612990679355,
  0.09065968278232492,
  0.11405318970244022],
 [0.18257418583505536,
  0.20519567041703082,
  0.22475645467377744,
  0.24175915408619977,
  0.2566196768304905],
 [0.3651483716701107,
  0.37619206243122316,
  0.38529677944076135,
  0.3928586253900746,
  0.39918616395854073],
 [0.5477225575051661,
  0.5471884544454155,
  0.5458371042077452,
  0.5439580966939495,
  0.541752651086591],
 [0.7302967433402214,
  0.7181848464596079,
  0.7063774289747291,
  0.6950575679978244,
  0.6843191382146413]]